branch-defaults:
  default:
    environment: ENVIRONMENT_NAME_HERE
global:
  application_name: football-predictor-backend
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: us-east-2
  workspace_type: Application
